#!/bin/bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}GLEC DTG - STM32 Firmware Build${NC}"
echo -e "${GREEN}========================================${NC}\n"

# Get project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$PROJECT_ROOT"

STM32_DIR="$PROJECT_ROOT/stm32-firmware"

# Parse arguments
ACTION=${1:-"build"}
MONITOR=false

for arg in "$@"; do
    case $arg in
        --monitor|-m)
            MONITOR=true
            shift
            ;;
    esac
done

echo -e "${BLUE}📋 Configuration:${NC}"
echo "  • STM32 Directory: $STM32_DIR"
echo "  • Action: $ACTION"
echo "  • Monitor: $MONITOR"
echo ""

# Check if STM32 directory exists
if [ ! -d "$STM32_DIR" ]; then
    echo -e "${YELLOW}⚠️  STM32 firmware directory not found${NC}"
    echo -e "${YELLOW}Creating directory structure...${NC}\n"

    mkdir -p "$STM32_DIR"/{Core/{Src,Inc},Drivers,build}

    # Create placeholder Makefile
    cat > "$STM32_DIR/Makefile" << 'EOF'
# GLEC DTG STM32 Firmware Makefile
# Placeholder - actual Makefile will be generated by STM32CubeMX

PROJECT = dtg_firmware
BUILD_DIR = build

# Toolchain
PREFIX = arm-none-eabi-
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size

# MCU
CPU = -mcpu=cortex-m4
FPU = -mfpu=fpv4-sp-d16
FLOAT-ABI = -mfloat-abi=hard
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# Dummy targets for now
.PHONY: all clean flash monitor

all:
	@echo "✅ Build target (placeholder)"
	@echo "ℹ️  Generate full Makefile using STM32CubeMX"
	@mkdir -p $(BUILD_DIR)
	@touch $(BUILD_DIR)/$(PROJECT).bin

clean:
	@echo "🧹 Cleaning build directory..."
	@rm -rf $(BUILD_DIR)/*
	@echo "✅ Clean complete"

flash: all
	@echo "📥 Flash target (placeholder)"
	@echo "ℹ️  Use: st-flash write $(BUILD_DIR)/$(PROJECT).bin 0x8000000"

monitor:
	@echo "🔌 Serial monitor (placeholder)"
	@echo "ℹ️  Use: screen /dev/ttyUSB0 115200"

size:
	@echo "📊 Size analysis (placeholder)"

EOF

    echo -e "${GREEN}✅ STM32 directory structure created${NC}"
    echo -e "${YELLOW}ℹ️  Generate full project using STM32CubeMX${NC}\n"
fi

cd "$STM32_DIR"

# Function to check dependencies
check_dependencies() {
    echo -e "${YELLOW}Checking dependencies...${NC}"

    local missing_deps=()

    # Check ARM GCC toolchain
    if ! command -v arm-none-eabi-gcc &> /dev/null; then
        missing_deps+=("arm-none-eabi-gcc")
    else
        GCC_VERSION=$(arm-none-eabi-gcc --version | head -n1)
        echo -e "${GREEN}✅ $GCC_VERSION${NC}"
    fi

    # Check make
    if ! command -v make &> /dev/null; then
        missing_deps+=("make")
    else
        echo -e "${GREEN}✅ make $(make --version | head -n1 | awk '{print $3}')${NC}"
    fi

    # Check st-flash (optional for build, required for flash)
    if [ "$ACTION" == "flash" ]; then
        if ! command -v st-flash &> /dev/null; then
            missing_deps+=("st-flash")
        else
            STFLASH_VERSION=$(st-flash --version 2>&1 | head -n1)
            echo -e "${GREEN}✅ $STFLASH_VERSION${NC}"
        fi
    fi

    if [ ${#missing_deps[@]} -gt 0 ]; then
        echo -e "\n${RED}❌ Missing dependencies: ${missing_deps[*]}${NC}"
        echo -e "\n${YELLOW}Install with:${NC}"
        echo "  Ubuntu/Debian: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi stlink-tools"
        echo "  macOS: brew install --cask gcc-arm-embedded && brew install stlink"
        exit 1
    fi

    echo ""
}

# Function to build firmware
build_firmware() {
    echo -e "${YELLOW}🔨 Building STM32 Firmware...${NC}\n"

    # Clean build
    if [ "$1" == "clean" ]; then
        echo -e "${YELLOW}Cleaning previous build...${NC}"
        make clean
        echo ""
    fi

    # Build
    echo -e "${YELLOW}Compiling...${NC}"
    if make -j$(nproc) all; then
        echo -e "\n${GREEN}✅ Build Successful!${NC}\n"

        # Show binary size
        if [ -f "build/dtg_firmware.bin" ]; then
            SIZE=$(stat -f%z "build/dtg_firmware.bin" 2>/dev/null || stat -c%s "build/dtg_firmware.bin" 2>/dev/null || echo "0")
            SIZE_KB=$((SIZE / 1024))
            echo -e "${BLUE}📊 Binary Size:${NC}"
            echo "  • Size: $SIZE bytes ($SIZE_KB KB)"

            # Calculate percentage (assuming 512KB flash)
            FLASH_SIZE=$((512 * 1024))
            PERCENT=$((SIZE * 100 / FLASH_SIZE))
            echo "  • Flash Usage: $PERCENT% of 512 KB"
            echo ""
        fi
    else
        echo -e "\n${RED}❌ Build Failed!${NC}"
        echo "Check build output above for errors"
        exit 1
    fi
}

# Function to flash firmware
flash_firmware() {
    echo -e "${YELLOW}📥 Flashing Firmware to STM32...${NC}\n"

    BIN_FILE="build/dtg_firmware.bin"

    if [ ! -f "$BIN_FILE" ]; then
        echo -e "${RED}❌ Binary file not found: $BIN_FILE${NC}"
        echo "Run build first"
        exit 1
    fi

    # Check if ST-Link is connected
    echo -e "${YELLOW}Checking ST-Link connection...${NC}"
    if ! st-info --probe &> /dev/null; then
        echo -e "${RED}❌ ST-Link not found!${NC}"
        echo "Please connect ST-Link debugger"
        exit 1
    fi

    echo -e "${GREEN}✅ ST-Link detected${NC}\n"

    # Flash
    echo -e "${YELLOW}Writing to flash memory...${NC}"
    if st-flash write "$BIN_FILE" 0x8000000; then
        echo -e "\n${GREEN}✅ Firmware Flashed Successfully!${NC}\n"

        # Reset device
        echo -e "${YELLOW}Resetting device...${NC}"
        st-flash reset
        echo -e "${GREEN}✅ Device reset${NC}\n"
    else
        echo -e "\n${RED}❌ Flash Failed!${NC}"
        echo "Try:"
        echo "  1. Disconnect and reconnect ST-Link"
        echo "  2. Press reset button on STM32"
        echo "  3. Check connections"
        exit 1
    fi
}

# Function to start serial monitor
start_monitor() {
    echo -e "${YELLOW}🔌 Starting Serial Monitor...${NC}"
    echo -e "${YELLOW}Baudrate: 115200${NC}"
    echo -e "${YELLOW}Press Ctrl+A then K to exit${NC}\n"
    echo -e "${BLUE}========================================${NC}\n"

    # Try different serial ports
    for PORT in /dev/ttyUSB0 /dev/ttyACM0 /dev/tty.usbserial* /dev/tty.usbmodem*; do
        if [ -e "$PORT" ]; then
            echo -e "${GREEN}Found serial port: $PORT${NC}\n"

            # Use screen if available, otherwise minicom
            if command -v screen &> /dev/null; then
                screen "$PORT" 115200
            elif command -v minicom &> /dev/null; then
                minicom -D "$PORT" -b 115200
            else
                echo -e "${RED}❌ No serial terminal found (screen or minicom)${NC}"
                echo "Install: sudo apt install screen"
                exit 1
            fi
            return
        fi
    done

    echo -e "${RED}❌ No serial port found${NC}"
    echo "Check USB connection"
}

# Main logic
check_dependencies

case $ACTION in
    build)
        build_firmware
        ;;
    clean)
        build_firmware clean
        ;;
    flash)
        build_firmware
        flash_firmware

        if [ "$MONITOR" = true ]; then
            start_monitor
        fi
        ;;
    monitor)
        start_monitor
        ;;
    *)
        echo -e "${RED}❌ Unknown action: $ACTION${NC}"
        echo "Available: build, clean, flash, monitor"
        exit 1
        ;;
esac

# Summary
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}✅ STM32 Firmware Process Complete!${NC}"
echo -e "${GREEN}========================================${NC}\n"

echo -e "${YELLOW}📋 Summary:${NC}"
echo "  • Action: $ACTION"
echo "  • Directory: $STM32_DIR"
echo ""

echo -e "${YELLOW}🚀 Next Steps:${NC}"
echo "  1. Test CAN communication: ${GREEN}candump can0${NC}"
echo "  2. Build Android JNI: ${GREEN}./.claude/skills/android-build/run.sh${NC}"
echo "  3. Test UART communication: ${GREEN}End-to-End test${NC}"
echo ""

echo -e "${GREEN}Firmware Ready! 🎉${NC}"
